clear
capture log close
#delimit;
set more off; 
cd  "F:\PPIE\THESIS_REAL\data_ifls\dari_ayu";
log using OUT\hhchar14, replace text;

*capture program drop sp93;
*program define sp93;

local j = 1;
while `j' <= 25 { ;
	tempfile p`j';
	tempfile q`j';
	tempfile r`j';
	local j = `j' + 1;
	};
global IN "F:\PPIE\THESIS_REAL\data_ifls\dari_ayu";
global OUT "F:\PPIE\THESIS_REAL\data_ifls\dari_ayu";
	
	
disp "******************************";
disp "* H4. Household expenditure   *";
disp "******************************";

**Food expenditure/week;
use "IN\2014\b1_ks1.dta", clear;
keep hhid14_9 ks1type ks02 ;
* membuat ks1type menjadi real sehingga dapat di-reshape menjadi wide;
gen r_ks1type = ks1type;
* makanan pokok;
replace r_ks1type="1" if ks1type=="A";
replace r_ks1type="2" if ks1type=="B";
replace r_ks1type="3" if ks1type=="C";
replace r_ks1type="4" if ks1type=="D";
replace r_ks1type="5" if ks1type=="E";
* sayur mayur;
replace r_ks1type="6" if ks1type=="F";
replace r_ks1type="7" if ks1type=="G";
replace r_ks1type="8" if ks1type=="H";
* makanan kering;
replace r_ks1type="9" if ks1type=="I";
replace r_ks1type="10" if r_ks1type=="J";
* daging/ikan;
replace r_ks1type="11" if r_ks1type=="K";
replace r_ks1type="12" if r_ks1type=="L";
replace r_ks1type="13" if r_ks1type=="M";
replace r_ks1type="14" if r_ks1type=="N";
* lauk pauk lainnya;
replace r_ks1type="15" if r_ks1type=="OA";
replace r_ks1type="16" if r_ks1type=="OB";
* susu/telur;
replace r_ks1type="17" if r_ks1type=="P";
replace r_ks1type="18" if r_ks1type=="Q";
* bumbu-bumbuan;
replace r_ks1type="19" if r_ks1type=="R";
replace r_ks1type="20" if r_ks1type=="S";
replace r_ks1type="21" if r_ks1type=="T";
replace r_ks1type="22" if r_ks1type=="U";
replace r_ks1type="23" if r_ks1type=="V";
replace r_ks1type="24" if r_ks1type=="W";
replace r_ks1type="25" if r_ks1type=="X";
replace r_ks1type="26" if r_ks1type=="Y";
replace r_ks1type="27" if r_ks1type=="Z";
replace r_ks1type="28" if r_ks1type=="AA";
replace r_ks1type="29" if r_ks1type=="BA";
replace r_ks1type="30" if r_ks1type=="CA";
replace r_ks1type="31" if r_ks1type=="DA";
replace r_ks1type="32" if r_ks1type=="EA";
replace r_ks1type="33" if r_ks1type=="FA";
replace r_ks1type="34" if r_ks1type=="GA";
replace r_ks1type="35" if r_ks1type=="HA";
replace r_ks1type="36" if r_ks1type=="IA";
replace r_ks1type="37" if r_ks1type=="IB";
*Mereshape data (food expenditure/week);
destring r_ks1type, replace;
drop ks1type;
reshape wide ks02 , i(hhid14_9) j(r_ks1type);
sort hhid14_9;
save `r1', replace; 

*Non food expenditure/month (more frequent goods);
use "IN\2014\b1_ks2.dta", clear;
keep hhid14_9 ks2type ks06;
* membuat ks2type menjadi real sehingga dapat di-reshape menjadi wide;
gen r_ks2type = ks2type;
replace r_ks2type="1" if ks2type=="A1";
replace r_ks2type="2" if ks2type=="A2";
replace r_ks2type="3" if ks2type=="A3";
replace r_ks2type="4" if ks2type=="A4";
replace r_ks2type="5" if ks2type=="B";
replace r_ks2type="6" if ks2type=="C";
replace r_ks2type="7" if ks2type=="C1";
replace r_ks2type="8" if ks2type=="D";
replace r_ks2type="9" if ks2type=="E";
replace r_ks2type="10" if ks2type=="F1";
replace r_ks2type="11" if ks2type=="F2";
replace r_ks2type="12" if ks2type=="G";
*Mereshape data (Non food expenditure/month (more frequent goods));
destring r_ks2type, replace;
tab r_ks2type, missing;
sum r_ks2type if hhid14_9=="293430003" & r_ks2type==12;
replace r_ks2type=12 if hhid14_9=="293430003" & r_ks2type==.;
tab r_ks2type, missing;
drop ks2type;
reshape wide ks06, i(hhid14_9) j(r_ks2type);
sort hhid14_9;
save `r2', replace; 

*Non food expenditure/year (less frequent goods);
use "IN\2014\b1_ks3.dta", clear;
keep hhid14_9 ks3type ks08 ks09a;
*membuat ks3type menjadi real sehingga dapat di-reshape menjadi wide;
gen r_ks3type = ks3type;
replace r_ks3type="1" if ks3type=="A";
replace r_ks3type="2" if ks3type=="B";
replace r_ks3type="3" if ks3type=="C";
replace r_ks3type="4" if ks3type=="D";
replace r_ks3type="5" if ks3type=="E";
replace r_ks3type="6" if ks3type=="F";
replace r_ks3type="7" if ks3type=="G";
*Mereshape data (Non food expenditure/year (less frequent goods));
destring r_ks3type, replace;
tab r_ks3type, missing;
drop ks3type;
reshape wide ks08 ks09a, i(hhid14_9) j(r_ks3type);
sort hhid14_9;
save `r3', replace; 

*Other expenditure;
use "IN\2014\b1_ks0.dta", clear;
* ks04b : Berapa rupiah nilai pangan yang diberikan pada pihak lain di luar rumah tangga dalam satu minggu terakhir?;
* ks10a. Kira-kira berapa jumlah biaya bersekolah (misalnya SPP, komite sekolah, praktikum/ketrampilan, uang pendaftaran, ujian-ujian, iuran lain seperti OSIS, uang daftar ulang) selama 1 tahun terakhir?;
* ks11a. Kira-kira berapa jumlah biaya untuk peralatan sekolah (misalnya untuk seragam sekolah, alat-alat perlengkapan sekolah, dsb) selama 1 tahun terakhir ?;
* ks12a. Kira-kira berapa jumlah biaya transport, uang saku dan kursus sehubungan dengan sekolah/kuliah selama 1 tahun terakhir ?;
* ks12b. Kira-kira berapa jumlah biaya kost/sewa kamar (termasuk biaya makan) yang dikeluarkan untuk [...] selama satu tahun terakhir?;
keep hhid14_9 ks04b ks10aa ks10ab ks11aa ks11ab ks12aa ks12ab ks12bb;
sort hhid14_9;
save `r4', replace; 

*housing expenditure;
use "IN\2014\b2_kr.dta", clear;
keep hhid14_9 kr03 kr04a kr04ax kr05a kr05ax;
qui gen kr0405 = kr04a/12 if (kr03==5)&(kr04ax==1);
qui replace kr0405 = kr04a if (kr03==5)&(kr04ax==2);
qui replace kr0405 = kr05a/12 if (kr03==1|kr03==2|kr03==95)&(kr05ax==1);
qui replace kr0405 = kr05a if (kr03==1|kr03==2|kr03==95)&(kr05ax==2);
label var kr0405 "Pengeluaran/perkiraan sewa rumah/bulan";
sort hhid14_9;
save `r5', replace; 

*Combine all expenditure;
* food expenditure;
use `r1', clear;
sort hhid14_9;
display _N;
* combine with non food expenditure (more frequent goods);
merge m:1 hhid14_9 using `r2';
rename _merge mrgr2;
sort hhid14_9;
display _N;
* combine with non food expenditure (less frequent goods);
merge m:1 hhid14_9 using `r3';
rename _merge mrgr3;
sort hhid14_9;
display _N;
* combine with other expenditure;
merge m:1 hhid14_9 using `r4';
rename _merge mrgr4;
sort hhid14_9;
display _N;
* combine with housing expenditure;
merge m:1 hhid14_9 using `r5';
rename _merge mrgr5;
sort hhid14_9;

display _N;
sort hhid14_9;
save `q4', replace; 

* food expenditure;
egen foodexpw = rowtotal(ks02* ks04b), missing;
label var foodexpw "Pengeluaran pangan per minggu" ;
count if foodexpw==.;
sum foodexpw;
gen foodexpm = food*4;
label var foodexpm "Pengeluaran pangan/bulan" ;
sum foodexpm;
qui gen foodexpm_gr=.;
replace foodexpm_gr=1 if foodexpm<=100000;
replace foodexpm_gr=2 if foodexpm>100000 & foodexpm<=500000;
replace foodexpm_gr=3 if foodexpm>500000 & foodexpm<=1000000;
replace foodexpm_gr=4 if foodexpm>1000000 & foodexpm!=.;
tab foodexpm_gr, missing;

* non food expenditure ;
* more frequent goods;
tab hhid14_9 if ks061==. & ks062==. & ks063==. & ks064==. & ks065==. & ks066==. & ks067==. & ks068==. & ks069==. & ks0610==. & ks0611==. & ks0612==.;
egen nfmfm = rowtotal(ks06*), missing;
label var nfmfm "Pengeluaran non pangan untuk barang yang lebih sering per bulan";
* less frequent goods;
tab hhid14_9 if ks081==. & ks082==. & ks083==. & ks084==. & ks085==. & ks086==. & ks087==.;
egen nflfy = rowtotal(ks08* ks09*), missing;
label var nflfy "Pengeluaran non pangan untuk barang yang tidak lebih sering per tahun";
gen nflfm = nflfy/12;
label var nflfm "Pengeluaran non pangan untuk barang yang tidak lebih sering per bulan";
* education;
tab hhid14_9 if ks10aa==. & ks10ab==. & ks11aa==. & ks11ab==. & ks12aa==. & ks12ab==. & ks12bb==.;
egen educexpy = rowtotal(ks10* ks11* ks12*), missing;
label var educexpy "Pengeluaran pendidikan per tahun";
gen educexpm = educexpy/12;
label var educexpm "Pengeluaran pendidikan per bulan";
* housing;
tab hhid14_9 if ks10aa==. & ks10ab==. & ks11aa==. & ks11ab==. & ks12aa==. & ks12ab==. & ks12bb==.;
gen hoexpm = kr0405;
label var hoexpm "Pengeluaran/perkiraan sewa rumah/bulan";
* all non food exp/month;
egen nfoodexpm= rowtotal (nfmfm nflfm educexpm hoexpm), missing;
count if nfoodexpm==.;
sum nfoodexpm;
* nfoodexpm>1.e+9: hhid14_9: "217080000" dan ks09a3:4.00000e+10 (pengeluaran untuk kesehatan setahun terakhir);
label var nfoodexpm "Pengeluaran non pangan/bulan";
qui gen nfoodexpm_gr=.;
replace nfoodexpm_gr=1 if nfoodexpm<=100000;
replace nfoodexpm_gr=2 if nfoodexpm>100000 & nfoodexpm<=500000;
replace nfoodexpm_gr=3 if nfoodexpm>500000 & nfoodexpm<=1000000;
replace nfoodexpm_gr=4 if nfoodexpm>1000000 & nfoodexpm!=.;
tab nfoodexpm_gr, missing;

** combine all expenditure;
egen expm = rowtotal(foodexpm nfoodexpm) if foodexpm!=., missing;
label var expm "Total pengeluaran rumah tangga/bulan";
count if expm==.;
list foodexpw foodexpm nfmfm nflfy nflfm educexpy educexpm hoexpm nfoodexpm if expm==.;
sum expm;
gen expmjt=expm/1000000;
label var expm "Total pengeluaran rumah tangga/bulan (juta)";
count if expmjt==.;
list foodexpw foodexpm nfmfm nflfy nflfm educexpy educexpm hoexpm nfoodexpm if expmjt==.;
sum expmjt;
gen expm_gr=.;
label var expm_gr "Kelompok total pengeluaran rumah tangga/bulan";
replace expm_gr=1 if expm<=1000000;
replace expm_gr=2 if expm>1000000 & expm<=5000000;
replace expm_gr=3 if expm>5000000 & expm<=10000000;
replace expm_gr=4 if expm>10000000 & expm!=.;
label define expmgr 1 "<1jt" 2 "1-5jt" 3 "5-10jt" 4 ">10jt";
label values expm_gr expmgr;
tab expm_gr, missing;	
sort hhid14_9;
display _N;
keep hhid14_9 expm expmjt ;
save `q4', replace; 

display _N;
save OUT\1306_hhchar14, replace; 
